#!/usr/bin/env python3
"""vlm_merge_dsl.py - Merge VLM-generated XML DSL with glm-ocr extracted data.

Uses a VLM API call to intelligently merge two sources:
  1. VLM XML (accurate layout/styling, may have OCR text errors)
  2. glm-ocr JSON (accurate text, no style info)

Usage:
    uv run --with requests,Pillow,lxml \
        .claude/skills/anything-to-docx/scripts/vlm_merge_dsl.py \
        --workspace /path/to/workspace --pages 10 --batch-size 8
"""

import argparse
import base64
import json
import os
import re
import shutil
import sys
import time

from io import BytesIO
from pathlib import Path

import requests
from lxml import etree
from PIL import Image


# ---------------------------------------------------------------------------
# VLM Configuration — override any value via environment variable
# ---------------------------------------------------------------------------

# LMStudio local endpoint; override with VLM_ENDPOINT env var for remote/cloud VLM
VLM_ENDPOINT = os.environ.get("VLM_ENDPOINT", "http://localhost:1234/v1/chat/completions")

# Default to qwen3.5-35b-a3b (local); override with VLM_MODEL env var
VLM_MODEL = os.environ.get("VLM_MODEL", "qwen3.5-35b-a3b")

# LMStudio ignores API keys, but OpenAI-compatible API requires the header
VLM_API_KEY = os.environ.get("VLM_API_KEY", "lm-studio")

# 10 min — an 8-page merge batch with images + OCR data takes ~3-5 min on consumer GPUs
API_TIMEOUT = int(os.environ.get("VLM_TIMEOUT", "600"))

# Qwen3.5 supports up to 128K output tokens; merged XML for 8 pages ≈ 20-40K tokens
API_MAX_TOKENS = int(os.environ.get("VLM_MAX_TOKENS", "131072"))

# 2 min between retries — unified with vlm_generate_dsl.py for consistency
API_RETRY_DELAY = int(os.environ.get("VLM_RETRY_DELAY", "120"))

# Merge images are only for visual verification, not OCR — 1200px saves ~60% tokens vs 1820px
IMAGE_MAX_WIDTH = int(os.environ.get("VLM_MERGE_IMAGE_WIDTH", "1200"))

# Low temperature for deterministic structured XML output
VLM_TEMPERATURE = float(os.environ.get("VLM_TEMPERATURE", "0.6"))

SYSTEM_PROMPT = """\
You are a document reconstruction expert. You must merge two sources of information to produce the most accurate XML DSL representation of document pages.

Source 1 (VLM XML): Generated by visual analysis. Strengths: accurate layout, styling, colors, font sizes, visual structure. Weaknesses: may have OCR text errors, especially for small or blurry text.

Source 2 (OCR JSON): Generated by glm-ocr. Strengths: accurate text content, reliable character recognition. Weaknesses: no style information, flat structure.

OCR JSON format per page (0-indexed array):
[
  {"index": 0, "label": "text|table|formula|image", "native_label": "doc_title|paragraph_title|text|table|image|figure_title|vision_footnote|display_formula", "content": "...", "bbox_2d": [x1,y1,x2,y2]}
]
Note: bbox_2d values are normalized 0-1000.

Merge rules:
1. USE VLM XML as the structural base (layout, element order, styling, colors, fonts)
2. REPLACE text content with OCR text when OCR text is clearly more accurate (no garbled characters, proper spacing)
3. KEEP VLM text when OCR text seems wrong or missing for that region
4. For tables: use VLM structure (rows/cols/merge) but prefer OCR cell text content
5. For images: keep VLM's <image> elements, set src to match OCR's cropped image naming: "ocr-output/input/imgs/cropped_page{P}_idx{M}.jpg" where P=page index (0-based), M=sequential image counter per page
6. Ensure all text from OCR appears somewhere in the output -- do not drop content
7. Preserve ALL styling attributes from VLM XML exactly
8. Output ONLY valid XML wrapped in <pages>...</pages>. No explanations."""


# ---------------------------------------------------------------------------
# Pure data loading functions
# ---------------------------------------------------------------------------


def clean_ocr_content(text):
    """Remove common OCR artifacts from content strings.

    Strips markdown code fences, stray leading slashes, and other
    noise that glm-ocr may inject into recognized text.
    """
    if not text or not isinstance(text, str):
        return text
    cleaned = re.sub(r"```(?:markdown|xml|json|html)?\s*```", "", text)
    cleaned = re.sub(r"```(?:markdown|xml|json|html)?\s*\n?\s*```", "", cleaned)
    cleaned = re.sub(r"^```(?:markdown|xml|json|html)?$", "", cleaned, flags=re.MULTILINE)
    cleaned = cleaned.strip()
    # Remove stray leading "/" from figure captions
    if cleaned.startswith("/ ") or cleaned.startswith("／ "):
        cleaned = cleaned[2:]
    return cleaned


def load_ocr_data(workspace):
    """Load glm-ocr JSON data. Returns list of lists (outer=pages, 0-indexed).

    Cleans OCR artifacts from content strings during loading.
    """
    ocr_path = Path(workspace) / "ocr-output" / "input" / "input.json"
    if not ocr_path.exists():
        print(f"Warning: OCR data not found at {ocr_path}", file=sys.stderr)
        return []
    with open(ocr_path, "r", encoding="utf-8") as f:
        data = json.load(f)
    if not isinstance(data, list):
        print(f"Warning: OCR data is not a list, got {type(data)}", file=sys.stderr)
        return []
    # Clean artifacts from OCR content
    for page in data:
        if not isinstance(page, list):
            continue
        for elem in page:
            if isinstance(elem, dict) and "content" in elem:
                original = elem["content"]
                cleaned = clean_ocr_content(original)
                if cleaned != original and cleaned == "":
                    # If cleaning removed everything, drop the element text
                    # but keep the element for structural purposes
                    elem["content"] = ""
                elif cleaned != original:
                    elem["content"] = cleaned
    return data


def load_ocr_markdown(workspace, max_chars=2000):  # First 2000 chars of OCR markdown — provides translation context without exceeding token budget
    """Load glm-ocr markdown content (truncated for context)."""
    md_path = Path(workspace) / "ocr-output" / "input" / "input.md"
    if not md_path.exists():
        return ""
    with open(md_path, "r", encoding="utf-8") as f:
        content = f.read()
    return content[:max_chars]


def load_vlm_xml(workspace, page_num):
    """Load VLM-generated XML for a page. Returns lxml Element or None."""
    xml_path = Path(workspace) / "dsl-vlm" / f"page-{page_num}.xml"
    if not xml_path.exists():
        return None
    with open(xml_path, "r", encoding="utf-8") as f:
        text = f.read().strip()
    try:
        return etree.fromstring(text.encode("utf-8"))
    except etree.XMLSyntaxError as e:
        print(f"Warning: Invalid XML in {xml_path}: {e}", file=sys.stderr)
        # Try wrapping in a root element
        try:
            return etree.fromstring(f"<wrapper>{text}</wrapper>".encode("utf-8"))
        except etree.XMLSyntaxError:
            return None


def load_vlm_xml_text(workspace, page_num):
    """Load VLM-generated XML as raw text for a page."""
    xml_path = Path(workspace) / "dsl-vlm" / f"page-{page_num}.xml"
    if not xml_path.exists():
        return None
    with open(xml_path, "r", encoding="utf-8") as f:
        return f.read().strip()


def load_page_image_b64(workspace, page_num, max_width=IMAGE_MAX_WIDTH):
    """Load and optionally resize a page image, return base64 string or None."""
    img_path = Path(workspace) / "input-images" / f"page-{page_num}.png"
    if not img_path.exists():
        return None
    try:
        img = Image.open(img_path)
        img.load()
    except Exception as e:
        print(f"Warning: Cannot open image {img_path}: {e}", file=sys.stderr)
        return None

    # Resize if wider than max_width (for token savings)
    w, h = img.size
    if w > max_width:
        ratio = max_width / w
        new_w = max_width
        new_h = round(h * ratio)
        img = img.resize((new_w, new_h), Image.LANCZOS)

    # Convert to RGB if needed
    if img.mode not in ("RGB", "L"):
        img = img.convert("RGB")

    buf = BytesIO()
    img.save(buf, "PNG")
    return base64.b64encode(buf.getvalue()).decode("utf-8")


# ---------------------------------------------------------------------------
# Batch construction
# ---------------------------------------------------------------------------


def make_page_batches(total_pages, batch_size):
    """Split 1..total_pages into batches. Returns list of (start, end) tuples (1-indexed, inclusive)."""
    batches = []
    for i in range(1, total_pages + 1, batch_size):
        end = min(i + batch_size - 1, total_pages)
        batches.append((i, end))
    return batches


def build_user_prompt(vlm_texts, ocr_pages, ocr_markdown, start_page, end_page):
    """Build the user prompt for a batch merge.

    Args:
        vlm_texts: dict mapping page_num -> VLM XML text
        ocr_pages: dict mapping page_num -> OCR JSON data (list of dicts)
        ocr_markdown: truncated markdown string
        start_page: first page in batch (1-indexed)
        end_page: last page in batch (1-indexed, inclusive)

    Returns:
        str: the formatted user prompt
    """
    vlm_parts = []
    for pn in range(start_page, end_page + 1):
        xml_text = vlm_texts.get(pn, "<!-- VLM XML not available -->")
        vlm_parts.append(f"--- Page {pn} ---\n{xml_text}")
    vlm_section = "\n\n".join(vlm_parts)

    ocr_parts = []
    for pn in range(start_page, end_page + 1):
        page_data = ocr_pages.get(pn, [])
        ocr_parts.append(f"--- Page {pn} (0-indexed: {pn - 1}) ---\n{json.dumps(page_data, ensure_ascii=False)}")
    ocr_section = "\n\n".join(ocr_parts)

    return f"""\
Merge these sources for pages {start_page}-{end_page}.

=== VLM XML (pages {start_page}-{end_page}) ===
{vlm_section}

=== OCR JSON (pages {start_page}-{end_page}, 0-indexed) ===
{ocr_section}

=== OCR Markdown (context) ===
{ocr_markdown}

Output the merged XML for all pages, wrapped in <pages>...</pages>."""


def build_messages(user_prompt, image_b64s):
    """Build the messages list for the VLM API call.

    Args:
        user_prompt: the text prompt
        image_b64s: list of base64-encoded images (may contain None entries, which are skipped)

    Returns:
        list: messages for the API
    """
    content_parts = []

    # Images first (for pages that have them)
    for img_b64 in image_b64s:
        if img_b64 is not None:
            content_parts.append({
                "type": "image_url",
                "image_url": {"url": f"data:image/png;base64,{img_b64}"},
            })

    # Text prompt last
    content_parts.append({"type": "text", "text": user_prompt})

    return [
        {"role": "system", "content": SYSTEM_PROMPT},
        {"role": "user", "content": content_parts},
    ]


# ---------------------------------------------------------------------------
# VLM API call
# ---------------------------------------------------------------------------


def call_vlm_merge(messages):
    """Call VLM API for merge. Returns raw response text or raises on failure."""
    payload = {
        "model": VLM_MODEL,
        "messages": messages,
        "temperature": VLM_TEMPERATURE,
        "max_tokens": API_MAX_TOKENS,
    }
    headers = {
        "Authorization": f"Bearer {VLM_API_KEY}",
        "Content-Type": "application/json",
    }

    try:
        resp = requests.post(VLM_ENDPOINT, json=payload, headers=headers, timeout=API_TIMEOUT)
        resp.raise_for_status()
    except requests.exceptions.ConnectionError:
        print(f"  ERROR: Cannot connect to VLM at {VLM_ENDPOINT}", file=sys.stderr)
        print(f"  FIX: Check LMStudio is running and model {VLM_MODEL} is loaded.", file=sys.stderr)
        raise
    except requests.exceptions.Timeout:
        print(f"  ERROR: VLM request timed out after {API_TIMEOUT}s", file=sys.stderr)
        print(f"  FIX: Increase VLM_TIMEOUT (current: {API_TIMEOUT}s) or reduce batch size.", file=sys.stderr)
        raise
    except requests.exceptions.HTTPError as e:
        print(f"  ERROR: VLM returned HTTP error: {e}", file=sys.stderr)
        print(f"  FIX: Check VLM server logs. Model may be out of memory.", file=sys.stderr)
        raise

    data = resp.json()
    # Handle thinking models: prefer 'content', fallback to 'reasoning_content'
    msg = data["choices"][0]["message"]
    content = msg.get("content", "") or ""
    if not content.strip():
        reasoning = msg.get("reasoning_content", "") or ""
        if reasoning.strip():
            print("  Warning: 'content' was empty, using 'reasoning_content' as fallback", file=sys.stderr)
            content = reasoning

    # Strip markdown code fences if present
    content = content.strip()
    if content.startswith("```"):
        content = content.split("\n", 1)[1].rsplit("```", 1)[0].strip()

    return content


def call_vlm_merge_with_retry(messages):
    """Call VLM merge with one retry on failure."""
    try:
        return call_vlm_merge(messages)
    except Exception as e:
        print(f"  VLM call failed: {e}. Retrying in {API_RETRY_DELAY}s...", file=sys.stderr)
        time.sleep(API_RETRY_DELAY)
        return call_vlm_merge(messages)  # Let this one propagate if it fails


# ---------------------------------------------------------------------------
# XML parsing helpers
# ---------------------------------------------------------------------------


def _clean_ocr_artifacts_in_xml(page_element):
    """Remove common OCR artifacts from text content within a parsed XML page."""
    for elem in page_element.iter():
        if elem.text:
            original = elem.text
            cleaned = re.sub(r"```(?:markdown|xml|json|html)?\s*```", "", original)
            cleaned = re.sub(r"```(?:markdown|xml|json|html)?", "", cleaned)
            cleaned = cleaned.strip()
            if cleaned != original:
                elem.text = cleaned if cleaned else None


def extract_pages_from_response(response_text, start_page, end_page):
    """Parse VLM response XML and extract individual page elements.

    Args:
        response_text: raw XML text from VLM (should be wrapped in <pages>)
        start_page: first page number expected (1-indexed)
        end_page: last page number expected (1-indexed, inclusive)

    Returns:
        dict mapping page_num -> XML text string for each page
    """
    # Ensure the response has a root element
    text = response_text.strip()

    # Try parsing directly
    try:
        root = etree.fromstring(text.encode("utf-8"))
    except etree.XMLSyntaxError:
        # Try wrapping in <pages> if not already
        if not text.startswith("<pages"):
            try:
                root = etree.fromstring(f"<pages>{text}</pages>".encode("utf-8"))
            except etree.XMLSyntaxError as e:
                print(f"  Warning: Cannot parse merged XML: {e}", file=sys.stderr)
                return {}
        else:
            print(f"  Warning: Cannot parse merged XML", file=sys.stderr)
            return {}

    pages = {}

    # Find <page> elements (direct children or nested)
    page_elements = root.findall(".//page")
    if not page_elements and root.tag == "page":
        page_elements = [root]

    for page_el in page_elements:
        # Clean OCR artifacts from merged XML
        _clean_ocr_artifacts_in_xml(page_el)

        num_attr = page_el.get("number")
        if num_attr is not None:
            try:
                page_num = int(num_attr)
            except ValueError:
                continue
        else:
            # Assign based on order
            continue

        page_xml = etree.tostring(page_el, encoding="unicode", pretty_print=True)
        pages[page_num] = page_xml

    # If we got no pages with explicit numbers, assign by order
    if not pages and page_elements:
        for i, page_el in enumerate(page_elements):
            # Clean OCR artifacts from merged XML
            _clean_ocr_artifacts_in_xml(page_el)

            page_num = start_page + i
            if page_num > end_page:
                break
            page_xml = etree.tostring(page_el, encoding="unicode", pretty_print=True)
            pages[page_num] = page_xml

    return pages


def count_elements(xml_text):
    """Count total elements in an XML string."""
    try:
        root = etree.fromstring(xml_text.encode("utf-8"))
        return len(list(root.iter()))
    except Exception:
        return 0


# ---------------------------------------------------------------------------
# Fallback: copy VLM XML as-is
# ---------------------------------------------------------------------------


def fallback_copy_vlm(workspace, page_num):
    """Copy VLM XML to output directory as-is."""
    src = Path(workspace) / "dsl-vlm" / f"page-{page_num}.xml"
    dst = Path(workspace) / "dsl" / f"page-{page_num}.xml"
    if src.exists():
        shutil.copy2(src, dst)
        print(f"  Page {page_num}: fallback copy from VLM XML")
    else:
        print(f"  Page {page_num}: WARNING - no VLM XML to copy", file=sys.stderr)


# ---------------------------------------------------------------------------
# Main processing
# ---------------------------------------------------------------------------


def process_batch(workspace, start_page, end_page, ocr_data, ocr_markdown, batch_idx, total_batches):
    """Process a single batch of pages.

    Args:
        workspace: workspace directory path
        start_page: first page (1-indexed)
        end_page: last page (1-indexed, inclusive)
        ocr_data: full OCR data (list of lists, 0-indexed)
        ocr_markdown: truncated markdown string
        batch_idx: current batch number (1-indexed)
        total_batches: total number of batches

    Returns:
        dict mapping page_num -> merged XML text, or empty dict on failure
    """
    print(f"Merge batch {batch_idx}/{total_batches}: pages {start_page}-{end_page}...")

    # Gather VLM XML texts
    vlm_texts = {}
    for pn in range(start_page, end_page + 1):
        text = load_vlm_xml_text(workspace, pn)
        if text is not None:
            vlm_texts[pn] = text

    # Gather OCR data per page (convert 0-indexed to 1-indexed page numbers)
    ocr_pages = {}
    for pn in range(start_page, end_page + 1):
        page_idx = pn - 1  # 0-indexed
        if page_idx < len(ocr_data) and ocr_data[page_idx]:
            ocr_pages[pn] = ocr_data[page_idx]
        else:
            ocr_pages[pn] = []

    # Check if any page is missing both sources
    pages_missing_ocr = [pn for pn in range(start_page, end_page + 1) if not ocr_pages.get(pn)]
    if pages_missing_ocr:
        print(f"  Note: OCR data missing for pages: {pages_missing_ocr}")

    # Load page images
    image_b64s = []
    for pn in range(start_page, end_page + 1):
        image_b64s.append(load_page_image_b64(workspace, pn))

    # Build prompt and messages
    user_prompt = build_user_prompt(vlm_texts, ocr_pages, ocr_markdown, start_page, end_page)
    messages = build_messages(user_prompt, image_b64s)

    # Call VLM
    try:
        response_text = call_vlm_merge_with_retry(messages)
    except Exception as e:
        print(f"  VLM merge failed for batch {batch_idx}: {e}", file=sys.stderr)
        return {}

    # Parse response
    merged_pages = extract_pages_from_response(response_text, start_page, end_page)

    if not merged_pages:
        print(f"  Warning: No pages extracted from VLM response for batch {batch_idx}", file=sys.stderr)

    return merged_pages


def main():
    parser = argparse.ArgumentParser(
        description="Merge VLM XML DSL with glm-ocr data using VLM API"
    )
    parser.add_argument("--workspace", required=True, help="Workspace directory path")
    parser.add_argument("--pages", required=True, type=int, help="Total page count")
    parser.add_argument("--batch-size", type=int, default=8, help="Pages per VLM batch (default: 8)")
    args = parser.parse_args()

    workspace = args.workspace
    total_pages = args.pages
    batch_size = args.batch_size

    # Create output directory
    output_dir = Path(workspace) / "dsl"
    os.makedirs(output_dir, exist_ok=True)

    # Load shared data
    ocr_data = load_ocr_data(workspace)
    ocr_markdown = load_ocr_markdown(workspace)
    print(f"Loaded OCR data: {len(ocr_data)} pages")

    # Build batches
    batches = make_page_batches(total_pages, batch_size)
    total_batches = len(batches)
    print(f"Processing {total_pages} pages in {total_batches} batch(es) (batch size: {batch_size})")

    # Process each batch
    for batch_idx, (start_page, end_page) in enumerate(batches, start=1):
        merged = process_batch(
            workspace, start_page, end_page,
            ocr_data, ocr_markdown,
            batch_idx, total_batches,
        )

        # Save results (or fallback)
        for pn in range(start_page, end_page + 1):
            if pn in merged:
                out_path = output_dir / f"page-{pn}.xml"
                with open(out_path, "w", encoding="utf-8") as f:
                    f.write(merged[pn])
                elem_count = count_elements(merged[pn])
                print(f"  Page {pn}: {elem_count} elements in merged XML")
            else:
                fallback_copy_vlm(workspace, pn)

    print(f"\nMerge complete. Output in: {output_dir}")


if __name__ == "__main__":
    main()
